#!/usr/bin/env php
<?php

require_once __DIR__.'/MiamKernel.php';

use Symfony\Framework\WebBundle\Console\Application;

$kernel = new MiamKernel('prod', false);

$application = new Application($kernel);
$application->run();