#!/usr/bin/env php
<?php

require_once __DIR__.'/MiamKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new MiamKernel('prod', false);

$application = new Application($kernel);
$application->run();
