#!/usr/bin/env php
<?php

require_once __DIR__.'/MiamKernel.php';

use Symfony\Framework\WebBundle\Console\Application;

$kernel = new MiamKernel('dev', true);

$application = new Application($kernel);
$application->run();