#!/usr/bin/env php
<?php

require_once __DIR__.'/GordonKernel.php';

use Symfony\Framework\WebBundle\Console\Application;

$kernel = new GordonKernel('dev', true);

$application = new Application($kernel);
$application->run();
